// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: user.proto

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserMicroService_GetUser_FullMethodName = "/UserMicroService/GetUser"
)

// UserMicroServiceClient is the client API for UserMicroService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserMicroServiceClient interface {
	GetUser(ctx context.Context, in *UserMicroRequest, opts ...grpc.CallOption) (*UserMicroResponse, error)
}

type userMicroServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserMicroServiceClient(cc grpc.ClientConnInterface) UserMicroServiceClient {
	return &userMicroServiceClient{cc}
}

func (c *userMicroServiceClient) GetUser(ctx context.Context, in *UserMicroRequest, opts ...grpc.CallOption) (*UserMicroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserMicroResponse)
	err := c.cc.Invoke(ctx, UserMicroService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserMicroServiceServer is the server API for UserMicroService service.
// All implementations must embed UnimplementedUserMicroServiceServer
// for forward compatibility.
type UserMicroServiceServer interface {
	GetUser(context.Context, *UserMicroRequest) (*UserMicroResponse, error)
	mustEmbedUnimplementedUserMicroServiceServer()
}

// UnimplementedUserMicroServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserMicroServiceServer struct{}

func (UnimplementedUserMicroServiceServer) GetUser(context.Context, *UserMicroRequest) (*UserMicroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserMicroServiceServer) mustEmbedUnimplementedUserMicroServiceServer() {}
func (UnimplementedUserMicroServiceServer) testEmbeddedByValue()                          {}

// UnsafeUserMicroServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserMicroServiceServer will
// result in compilation errors.
type UnsafeUserMicroServiceServer interface {
	mustEmbedUnimplementedUserMicroServiceServer()
}

func RegisterUserMicroServiceServer(s grpc.ServiceRegistrar, srv UserMicroServiceServer) {
	// If the following call panics, it indicates UnimplementedUserMicroServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserMicroService_ServiceDesc, srv)
}

func _UserMicroService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMicroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMicroServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserMicroService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMicroServiceServer).GetUser(ctx, req.(*UserMicroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserMicroService_ServiceDesc is the grpc.ServiceDesc for UserMicroService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserMicroService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserMicroService",
	HandlerType: (*UserMicroServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserMicroService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
